### ISSUE TITLE
missing thirdpartylibs.xml file.

### ISSUE THREAD

**Issue by danmarsden** [simonefranza/moodle-mod_learninggoalwidget#1]
When including an external library (like d3) n your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://moodledev.io/docs/apis/commonfiles#thirdpartylibsxml
And here:
https://moodledev.io/general/community/plugincontribution/thirdpartylibraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by simonefranza** [comment]
Hello, thank you for opening this issue!

The [thirdpartylibs.xml](https://github.com/simonefranza/moodle-mod_learninggoalwidget/blob/104c615e5635f5bf6339584dd279432d9e2a0627/thirdpartylibs.xml) file exists already, is there anything missing in it?

**Comment by danmarsden** [comment]
nah - that looks like it's there - might have been running through the review too quick...
