### ISSUE TITLE
namespace needs to be changed.

### ISSUE THREAD

**Issue by purnendudash** [simonefranza/moodle-mod_learninggoalwidget#9]
Please refer to https://moodledev.io/general/development/policies/codingstyle#rules-for-level2

Your custom namespaces like fonts, help, event, model, pdf, report or privacy violate this naming rule. There are good reasons why it should be followed, mainly to avoid potential conflicts in the future. All these should be under classes/local/ namespace.

https://github.com/simonefranza/moodle-mod_learninggoalwidget/blob/adeebcade8d6a5a332db695e028be05b29dd5a06/classes/event/learninggoal_updated.php#L18

**Comment by mudrd8mz** [comment]
I am a bit confused now. I can't see custom namespaces here at the moment:
![image](https://github.com/simonefranza/moodle-mod_learninggoalwidget/assets/85831/abff7e03-5550-43fc-8f66-df7a8323e100)

All "event", "output" and "privacy" are Moodle subsystems and so the folders are expected here.

**Comment by purnendudash** [comment]
Should not it be under local folder?

**Comment by mudrd8mz** [comment]
I don't think so. As the "Rules for level2" says: It must be _either_ some API/subsystem, _or_ "local". Please refer to the standard plugins for examples.

**Comment by purnendudash** [comment]
@mudrd8mz Thanks for the clarification. I understood it now.
